import AdminNavbar from "@/components/AdminNavbar";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Admin Dashboard",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`flex flex-row overflow-y-hidden`}>
        <AdminNavbar />
        {children}
    </body>
    </html>
  );
}
