import AdminNavbar from "@/components/AdminNavbar";
import type { Metadata } from "next";
import AdminHeader from "@/components/AdminHeader";

export const metadata: Metadata = {
  title: "Admin Dashboard",
  description: "Generated by create next app",
};
const orgName = "Consejo Civico";
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`flex flex-row w-full`}>
        <AdminNavbar />
        <div className="flex flex-col w-full h-full bg-primary p-4">
          <AdminHeader />
          {children}
        </div>
      </body>
    </html>
  );
}
